name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: setup-maven-settings
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "github", "SagenKoder": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

    - name: Publish to GitHub
      run: mvn -Dmaven.wagon.http.pool=false clean deploy
